name: Empyrical CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python_venv: ['2.7_v1', '2.7_v2', '2.7_v3', '3.5_v1', '3.5_v2', '3.6']
        include:
          - python_venv: '2.7_v1'
            python: 2.7
            pandas: 0.18.1
            numpy: 1.11.1
            scipy: 0.17.1
            libgfortran: 3.0
          - python_venv: '2.7_v2'
            python: 2.7
            pandas: 0.19.2
            numpy: 1.12.1
            scipy: 0.19.0
            libgfortran: 3.0
          - python_venv: '2.7_v3'
            python: 2.7
            pandas: 0.20.1
            numpy: 1.12.1
            scipy: 0.19.0
            libgfortran: 3.0
          - python_venv: '3.5_v1'
            python: 3.5
            pandas: 0.18.1
            numpy: 1.11.1
            scipy: 0.17.1
            libgfortran: 3.0
          - python_venv: '3.5_v2'
            python: 3.5
            pandas: 0.19.2
            numpy: 1.12.1
            scipy: 0.19.0
            libgfortran: 3.0
          - python_venv: '3.6'
            python: 3.6
            pandas: 0.20.1
            numpy: 1.12.1
            scipy: 0.19.0
            libgfortran: 3.0

    name: py${{ matrix.python_venv }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup conda
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda

      - name: Install dependencies
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -n testenv --yes -c conda-forge pip python=${{ matrix.python }} numpy=${{ matrix.numpy }} pandas=${{ matrix.pandas }} scipy=${{ matrix.scipy }} libgfortran=${{ matrix.libgfortran }}
          source activate testenv
          pip install -e .[dev]
        shell: bash

      - name: Linting
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testenv
          flake8 .

      - name: Tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testenv
          nosetests

